const stories=[
['Microsoft','MSFT','Technology','Microsoft doubles down on AI infrastructure with record data center investment','Bloomberg','18 min','1667984390527-850f63192709'],
['Walmart','WMT','Retail','Walmart raises full-year outlook as value-conscious shoppers drive growth','Reuters','32 min','1601598851547-4302969d0614'],
['JPMorgan Chase','JPM','Finance','JPMorgan expands private credit team amid surging institutional demand','Financial Times','47 min','1486406146926-c627a92ad1ab'],
['Exxon Mobil','XOM','Energy','Exxon outlines new carbon capture project along the Gulf Coast','CNBC','1 hr','1504917595217-d4dc5ebe6122'],
['Amazon','AMZN','Technology','Amazon introduces next-generation fulfillment robots across U.S. network','The Verge','1 hr','1586528116311-ad8dd3c8310d'],
['UnitedHealth Group','UNH','Healthcare','UnitedHealth accelerates digital care investment in regional markets','WSJ','2 hrs','1576091160399-112ba8d25d1d'],
['Apple','AAPL','Technology','Apple supplier network prepares for expanded U.S. manufacturing push','Bloomberg','2 hrs','1517336714731-489689fd1ca8'],
['CVS Health','CVS','Healthcare','CVS unveils streamlined pharmacy benefits model for employers','Fortune','3 hrs','1587854692152-cbe660dbde88'],
['Berkshire Hathaway','BRK.B','Finance','Berkshire portfolio companies increase capital spending for the year','Barron’s','3 hrs','1611974789855-9c2a0a7236a3'],
['Ford Motor','F','Automotive','Ford reshapes EV roadmap with focus on affordable commercial vehicles','Reuters','4 hrs','1551830820-330a71b99659'],
['Costco','COST','Retail','Costco membership renewal rates reach another all-time high','CNBC','4 hrs','1604719312566-8912e9227c6a'],
['Alphabet','GOOGL','Technology','Alphabet cloud division wins major multi-year enterprise contracts','The Information','5 hrs','1573804633927-bfcbcd909acd'],
['Chevron','CVX','Energy','Chevron advances deepwater project after regulatory approval','Bloomberg','5 hrs','1516939884455-1445c8652f83'],
['General Motors','GM','Automotive','GM reports strong demand for new electric SUV lineup','Detroit Free Press','6 hrs','1492144534655-ae79c964c9d7'],
['McKesson','MCK','Healthcare','McKesson expands oncology platform through strategic acquisition','Reuters','6 hrs','1538108149393-fbbd81895907'],
['Cencora','COR','Healthcare','Cencora opens advanced distribution center to improve resilience','Modern Healthcare','7 hrs','1559757148-5c350d0d3c56'],
['Meta Platforms','META','Technology','Meta rolls out new business AI tools across messaging platforms','TechCrunch','7 hrs','1633675254053-d96c7668c3b8'],
['Home Depot','HD','Retail','Home Depot sees early signs of recovery in big-ticket renovation demand','WSJ','8 hrs','1581783898377-1c85bf937427'],
['Bank of America','BAC','Finance','Bank of America adds digital features for small business customers','American Banker','8 hrs','1559526324-593bc073d938'],
['Cardinal Health','CAH','Healthcare','Cardinal Health lifts guidance on resilient medical products demand','MarketWatch','9 hrs','1584982751601-97dcc096659c']];
const sectors=['All sectors','Technology','Finance','Healthcare','Retail','Energy','Automotive'];let active='All sectors',query='',saved=new Set();
const img=s=>`https://images.unsplash.com/photo-${s[6]}?auto=format&fit=crop&w=1000&q=85`;const icon=(n)=>n==='search'?'⌕':n==='save'?'♧':'↗';
function logo(){return `<div class="logo"><span>F</span><div>FORTUNE<small>BRIEF</small></div></div>`}
function render(){const data=stories.filter(s=>(active==='All sectors'||s[2]===active)&&`${s[0]} ${s[3]}`.toLowerCase().includes(query.toLowerCase()));const lead=data[0];document.querySelector('#root').innerHTML=`
<header><div class="nav wrap">${logo()}<nav><a class="active">Top stories</a><a href="#latest">Latest</a><a href="#sectors">Sectors</a><a href="#companies">Companies</a></nav><div class="nav-actions"><button class="icon" aria-label="Search">⌕</button><button class="watch">♧ Watchlist <b>${saved.size}</b></button><button class="menu">☰</button></div></div></header>
<div class="market"><div class="wrap tape"><span class="live"><i></i> MARKETS OPEN</span><span>S&amp;P 500 <b>5,638.21</b> <em>+0.42%</em></span><span>DOW <b>41,198.08</b> <em>+0.18%</em></span><span>NASDAQ <b>17,997.35</b> <em>+0.57%</em></span><span class="date">WEDNESDAY, SEPTEMBER 23</span></div></div>
<main class="wrap"><section class="intro"><div><p class="eyebrow">THE DAILY BRIEFING</p><h1>Today's top 20</h1><p>The essential stories moving America’s largest companies.</p></div><div class="edition"><span>◷</span><span>Last updated<br><b>10:42 AM ET</b></span></div></section>
<section class="tools" id="sectors"><div class="chips">${sectors.map(x=>`<button data-sector="${x}" class="${active===x?'selected':''}">${x}</button>`).join('')}</div><label class="search">⌕<input value="${query}" placeholder="Search companies"></label></section>
${lead?`<article class="hero"><div class="hero-img" style="background-image:linear-gradient(90deg,rgba(6,19,16,.15),transparent),url(${img(lead)})"><span class="rank">01</span></div><div class="hero-copy"><div class="story-top"><span class="company">▣ ${lead[0]}</span><button data-save="${lead[1]}" class="book ${saved.has(lead[1])?'saved':''}">${saved.has(lead[1])?'◆':'♧'}</button></div><h2>${lead[3]}</h2><p>The company is accelerating its strategy as enterprise and consumer demand continues to climb.</p><div class="meta"><b>${lead[4]}</b><span>•</span><span>${lead[5]} ago</span><span>•</span><span>4 min read</span></div><a href="#latest">Read full story ↗</a></div></article><div class="section-head" id="latest"><div><span>LATEST INTELLIGENCE</span><h2>More stories</h2></div><p>${data.length} of 20 stories⌄</p></div><section class="grid">${data.slice(1).map((s,i)=>`<article class="card"><div class="thumb" style="background-image:url(${img(s)})"><span class="rank">${String(i+2).padStart(2,'0')}</span><span class="sector">${s[2]}</span></div><div class="card-body"><div class="story-top"><span class="company">${s[0]} <small>${s[1]}</small></span><button data-save="${s[1]}" class="book ${saved.has(s[1])?'saved':''}">${saved.has(s[1])?'◆':'♧'}</button></div><h3>${s[3]}</h3><div class="meta"><b>${s[4]}</b><span>•</span><span>${s[5]} ago</span></div></div></article>`).join('')}</section>`:`<div class="empty"><h2>No stories found</h2><p>Try another company or sector.</p><button id="clear">Clear filters</button></div>`}</main>
<section class="newsletter"><div class="wrap"><div><span>STAY AHEAD</span><h2>The briefing, before the bell.</h2><p>Market-moving Fortune 500 news, delivered every weekday morning.</p></div><form><input type="email" placeholder="Work email address" required><button>Join the briefing ↗</button></form></div></section><footer class="wrap">${logo()}<p>Independent intelligence on America’s largest companies.</p><span>© 2026 FortuneBrief</span></footer>`;bind()}
function bind(){document.querySelectorAll('[data-sector]').forEach(b=>b.onclick=()=>{active=b.dataset.sector;render()});const q=document.querySelector('.search input');q.oninput=e=>{query=e.target.value;render();document.querySelector('.search input')?.focus()};document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{saved.has(b.dataset.save)?saved.delete(b.dataset.save):saved.add(b.dataset.save);render()});document.querySelector('form').onsubmit=e=>{e.preventDefault();e.currentTarget.innerHTML='<strong>✓ You’re on the list.</strong>'};document.querySelector('#clear')?.addEventListener('click',()=>{active='All sectors';query='';render()})}render();
